apiVersion: v1
kind: ConfigMap
metadata:
  name: arash-db-config
  namespace: grupp3
data:
  db-name: arash_guestbook
  db-host: arash-postgres
  db-port: "5432"
  db-user: postgres
  redis-host: arash-redis
  redis-port: "6379"
