apiVersion: v1
kind: Secret
metadata:
  name: quay-io-secret
  namespace: grupp3
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJRVTVXdzRST1JFRlNUa0ZOVGpwTXc1WlRSVTVPVWtRPSIKICAgIH0KICB9Cn0K
