---
# Database Password Secret
apiVersion: v1
kind: Secret
metadata:
  name: arash-db-password
  namespace: grupp3
type: Opaque
stringData:
  username: postgres
  password: arash-password-123

---
# Redis Password Secret
apiVersion: v1
kind: Secret
metadata:
  name: arash-redis-password
  namespace: grupp3
type: Opaque
stringData:
  password: arash-redis-password-123
